### PR TITLE
feat: drizzle schema representing database

### PR DESCRIPTION
**Pull request by odin5on**
Not ready to merge.  

Josh, I wanted to get back here and finish the things I started. Namely the Crew section. Also using drizzle and zod. Here is the drizzle schema I made based off of v3_database.sql. Take a look and let me know if it all looks good to you. I will be adding more commits, but wanted to make sure this is looking good.

### CODE REVIEW

**Comment by odin5on** [comment]
Realized /database/v3/old_sql_scripts/create_new schema.sql has a slightly more updated one. Just adds a few more objects, I will update

**Comment by joshuawootonn** [comment]
Hey @odin5on! Thanks for doing this. I have passed on this project to @Timbobeek. 

@Timbobeek maybe you can look into drizzle and check out how @odin5on and I are using it in the project?

**Comment by Timbobeek** [comment]
Will look into it!

-Tim

**Comment by joshuawootonn** [comment]
Generally, I think it would be great to use `drizzle-kit`. Here is a quote of what it does:

> Drizzle Kit — is a CLI companion for automatic SQL migrations generation and rapid prototyping.

https://orm.drizzle.team/kit-docs/overview


This will allow you to check your schema against the current schema. When you run:
```
drizzle-kit generate
```

and there is no longer a migration created then you know that the schema matches your database exactly. 

This will also make modifying the schema overtime easier.

**Review by joshuawootonn — COMMENTED** [review]
Closing this for now.

**Pull request closed without merging**
